	db EVOLVE_LEVEL, 36, MACHAMP
	db EVOLVE_ITEM, SUNSTONE, MACHAMP
	db 0 ; no more evolutions
	db 1, LOW_KICK
	db 1, LEER
	db 13, KARATE_CHOP
	db 17, ROCK_SLIDE
	db 20, SCARY_FACE
	db 24, BULLET_PUNCH
	db 31, STRENGTH
	db 35, FIRE_PUNCH
	db 42, ICE_PUNCH
	db 48, SEISMIC_TOSS
	db 54, DYNAMICPUNCH
	db 60, CROSS_CHOP
	db 66, DOUBLE_EDGE
	db 70, THUNDER_PUNCH
	db 73, POISON_JAB
	db 76, EARTHQUAKE
	db 0 ; no more level-up moves