	db 0 ; no more evolutions
	db 1, TACKLE
	db 15, TAKE_DOWN
	db 22, BULLET_PUNCH
	db 24, METAL_CLAW
	db 27, ZEN_HEADBUTT
	db 30, FLASH_CANNON
	db 34, PSYCHIC
	db 38, REFLECT
	db 42, SCARY_FACE
	db 48, THUNDER_PUNCH
	db 52, METEOR_MASH
	db 57, LIGHT_SCREEN
	db 62, IRON_DEFENSE
	db 72, ICE_PUNCH
	db 82, HYPER_BEAM
	db 87, EARTHQUAKE
	db 0 ; no more level-up moves
